# Generated by Django 2.2.4 on 2019-10-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('NameAc', models.TextField()),
                ('idAc', models.AutoField(primary_key=True, serialize=False)),
                ('AcMov', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('NameDir', models.TextField()),
                ('idDir', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
