# Generated by Django 2.2.4 on 2019-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvback', '0002_actor_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Cover',
            new_name='contentRating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Gender',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='idMovie',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Year',
            new_name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='gender',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='source',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
