# Generated by Django 2.2.4 on 2019-11-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvback', '0003_auto_20191028_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedMovie',
            fields=[
                ('IDRM', models.AutoField(primary_key=True, serialize=False)),
                ('Movies', models.ManyToManyField(to='mvback.Movie')),
            ],
        ),
    ]
