# Generated by Django 2.2.4 on 2019-11-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvback', '0004_recommendedmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='identifier',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
