# Generated by Django 2.2.4 on 2019-11-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvback', '0006_auto_20191117_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
