# Generated by Django 2.2.4 on 2020-05-13 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvback', '0007_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.BooleanField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvback.Movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvback.User')),
            ],
        ),
    ]
