# Generated by Django 2.2.4 on 2020-05-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvback', '0008_auto_20200513_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(error_messages={'unique': 'Este correo ya se encuentra registrado.'}, max_length=254, unique=True),
        ),
    ]
